package com.weimi.wmmess.business.shimu.bean.problem;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.weimi.wmmess.business.shimu.bean.DaoSession;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PROBLEM_RESBEAN".
*/
public class ProblemResbeanDao extends AbstractDao<ProblemResbean, Long> {

    public static final String TABLENAME = "PROBLEM_RESBEAN";

    /**
     * Properties of entity ProblemResbean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ProblemId = new Property(0, Long.class, "problemId", true, "_id");
        public final static Property CurrentStepIsChecked = new Property(1, boolean.class, "currentStepIsChecked", false, "CURRENT_STEP_IS_CHECKED");
    }

    private DaoSession daoSession;


    public ProblemResbeanDao(DaoConfig config) {
        super(config);
    }
    
    public ProblemResbeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PROBLEM_RESBEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: problemId
                "\"CURRENT_STEP_IS_CHECKED\" INTEGER NOT NULL );"); // 1: currentStepIsChecked
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PROBLEM_RESBEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ProblemResbean entity) {
        stmt.clearBindings();
 
        Long problemId = entity.getProblemId();
        if (problemId != null) {
            stmt.bindLong(1, problemId);
        }
        stmt.bindLong(2, entity.getCurrentStepIsChecked() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ProblemResbean entity) {
        stmt.clearBindings();
 
        Long problemId = entity.getProblemId();
        if (problemId != null) {
            stmt.bindLong(1, problemId);
        }
        stmt.bindLong(2, entity.getCurrentStepIsChecked() ? 1L: 0L);
    }

    @Override
    protected final void attachEntity(ProblemResbean entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ProblemResbean readEntity(Cursor cursor, int offset) {
        ProblemResbean entity = new ProblemResbean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // problemId
            cursor.getShort(offset + 1) != 0 // currentStepIsChecked
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ProblemResbean entity, int offset) {
        entity.setProblemId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCurrentStepIsChecked(cursor.getShort(offset + 1) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ProblemResbean entity, long rowId) {
        entity.setProblemId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ProblemResbean entity) {
        if(entity != null) {
            return entity.getProblemId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ProblemResbean entity) {
        return entity.getProblemId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
