package com.weimi.wmmess.business.shimu.bean.step3;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.weimi.wmmess.business.shimu.bean.DaoSession;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MOVE_SIDE_RESBEAN".
*/
public class MoveSideResbeanDao extends AbstractDao<MoveSideResbean, Long> {

    public static final String TABLENAME = "MOVE_SIDE_RESBEAN";

    /**
     * Properties of entity MoveSideResbean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MoveSideResbeanId = new Property(1, Long.class, "moveSideResbeanId", false, "moveSideResbeanId");
        public final static Property Index = new Property(2, int.class, "index", false, "INDEX");
        public final static Property Record = new Property(3, String.class, "record", false, "RECORD");
    }

    private Query<MoveSideResbean> step3MuResBean_MoveSideResbeanListQuery;

    public MoveSideResbeanDao(DaoConfig config) {
        super(config);
    }
    
    public MoveSideResbeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MOVE_SIDE_RESBEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"moveSideResbeanId\" INTEGER," + // 1: moveSideResbeanId
                "\"INDEX\" INTEGER NOT NULL ," + // 2: index
                "\"RECORD\" TEXT);"); // 3: record
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MOVE_SIDE_RESBEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MoveSideResbean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long moveSideResbeanId = entity.getMoveSideResbeanId();
        if (moveSideResbeanId != null) {
            stmt.bindLong(2, moveSideResbeanId);
        }
        stmt.bindLong(3, entity.getIndex());
 
        String record = entity.getRecord();
        if (record != null) {
            stmt.bindString(4, record);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MoveSideResbean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long moveSideResbeanId = entity.getMoveSideResbeanId();
        if (moveSideResbeanId != null) {
            stmt.bindLong(2, moveSideResbeanId);
        }
        stmt.bindLong(3, entity.getIndex());
 
        String record = entity.getRecord();
        if (record != null) {
            stmt.bindString(4, record);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MoveSideResbean readEntity(Cursor cursor, int offset) {
        MoveSideResbean entity = new MoveSideResbean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // moveSideResbeanId
            cursor.getInt(offset + 2), // index
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // record
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MoveSideResbean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMoveSideResbeanId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setIndex(cursor.getInt(offset + 2));
        entity.setRecord(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MoveSideResbean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MoveSideResbean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MoveSideResbean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "moveSideResbeanList" to-many relationship of Step3MuResBean. */
    public List<MoveSideResbean> _queryStep3MuResBean_MoveSideResbeanList(Long moveSideResbeanId) {
        synchronized (this) {
            if (step3MuResBean_MoveSideResbeanListQuery == null) {
                QueryBuilder<MoveSideResbean> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.MoveSideResbeanId.eq(null));
                step3MuResBean_MoveSideResbeanListQuery = queryBuilder.build();
            }
        }
        Query<MoveSideResbean> query = step3MuResBean_MoveSideResbeanListQuery.forCurrentThread();
        query.setParameter(0, moveSideResbeanId);
        return query.list();
    }

}
