package com.weimi.wmmess.business.shimu.bean.step3;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.weimi.wmmess.business.shimu.bean.DaoSession;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STEP3_SHUI_LU_DATE".
*/
public class Step3ShuiLuDateDao extends AbstractDao<Step3ShuiLuDate, Long> {

    public static final String TABLENAME = "STEP3_SHUI_LU_DATE";

    /**
     * Properties of entity Step3ShuiLuDate.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ShuiLuDateId = new Property(1, Long.class, "shuiLuDateId", false, "shuiLuDateId");
        public final static Property Index = new Property(2, int.class, "index", false, "INDEX");
        public final static Property Record = new Property(3, String.class, "record", false, "RECORD");
    }

    private Query<Step3ShuiLuDate> step3MuResBean_ShuiLuDateListQuery;

    public Step3ShuiLuDateDao(DaoConfig config) {
        super(config);
    }
    
    public Step3ShuiLuDateDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STEP3_SHUI_LU_DATE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"shuiLuDateId\" INTEGER," + // 1: shuiLuDateId
                "\"INDEX\" INTEGER NOT NULL ," + // 2: index
                "\"RECORD\" TEXT);"); // 3: record
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STEP3_SHUI_LU_DATE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Step3ShuiLuDate entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long shuiLuDateId = entity.getShuiLuDateId();
        if (shuiLuDateId != null) {
            stmt.bindLong(2, shuiLuDateId);
        }
        stmt.bindLong(3, entity.getIndex());
 
        String record = entity.getRecord();
        if (record != null) {
            stmt.bindString(4, record);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Step3ShuiLuDate entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long shuiLuDateId = entity.getShuiLuDateId();
        if (shuiLuDateId != null) {
            stmt.bindLong(2, shuiLuDateId);
        }
        stmt.bindLong(3, entity.getIndex());
 
        String record = entity.getRecord();
        if (record != null) {
            stmt.bindString(4, record);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Step3ShuiLuDate readEntity(Cursor cursor, int offset) {
        Step3ShuiLuDate entity = new Step3ShuiLuDate( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // shuiLuDateId
            cursor.getInt(offset + 2), // index
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // record
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Step3ShuiLuDate entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setShuiLuDateId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setIndex(cursor.getInt(offset + 2));
        entity.setRecord(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Step3ShuiLuDate entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Step3ShuiLuDate entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Step3ShuiLuDate entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "shuiLuDateList" to-many relationship of Step3MuResBean. */
    public List<Step3ShuiLuDate> _queryStep3MuResBean_ShuiLuDateList(Long shuiLuDateId) {
        synchronized (this) {
            if (step3MuResBean_ShuiLuDateListQuery == null) {
                QueryBuilder<Step3ShuiLuDate> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ShuiLuDateId.eq(null));
                step3MuResBean_ShuiLuDateListQuery = queryBuilder.build();
            }
        }
        Query<Step3ShuiLuDate> query = step3MuResBean_ShuiLuDateListQuery.forCurrentThread();
        query.setParameter(0, shuiLuDateId);
        return query.list();
    }

}
