package com.weimi.wmmess.business.shimu.bean.step3;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.weimi.wmmess.business.shimu.bean.DaoSession;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STEP3_MU_RES_BEAN".
*/
public class Step3MuResBeanDao extends AbstractDao<Step3MuResBean, Long> {

    public static final String TABLENAME = "STEP3_MU_RES_BEAN";

    /**
     * Properties of entity Step3MuResBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Step3Id = new Property(0, Long.class, "step3Id", true, "_id");
        public final static Property CurrentStepIsChecked = new Property(1, boolean.class, "currentStepIsChecked", false, "CURRENT_STEP_IS_CHECKED");
    }

    private DaoSession daoSession;


    public Step3MuResBeanDao(DaoConfig config) {
        super(config);
    }
    
    public Step3MuResBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STEP3_MU_RES_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: step3Id
                "\"CURRENT_STEP_IS_CHECKED\" INTEGER NOT NULL );"); // 1: currentStepIsChecked
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STEP3_MU_RES_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Step3MuResBean entity) {
        stmt.clearBindings();
 
        Long step3Id = entity.getStep3Id();
        if (step3Id != null) {
            stmt.bindLong(1, step3Id);
        }
        stmt.bindLong(2, entity.getCurrentStepIsChecked() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Step3MuResBean entity) {
        stmt.clearBindings();
 
        Long step3Id = entity.getStep3Id();
        if (step3Id != null) {
            stmt.bindLong(1, step3Id);
        }
        stmt.bindLong(2, entity.getCurrentStepIsChecked() ? 1L: 0L);
    }

    @Override
    protected final void attachEntity(Step3MuResBean entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Step3MuResBean readEntity(Cursor cursor, int offset) {
        Step3MuResBean entity = new Step3MuResBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // step3Id
            cursor.getShort(offset + 1) != 0 // currentStepIsChecked
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Step3MuResBean entity, int offset) {
        entity.setStep3Id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCurrentStepIsChecked(cursor.getShort(offset + 1) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Step3MuResBean entity, long rowId) {
        entity.setStep3Id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Step3MuResBean entity) {
        if(entity != null) {
            return entity.getStep3Id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Step3MuResBean entity) {
        return entity.getStep3Id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
