package com.weimi.wmmess.business.shimu.bean.step4;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.weimi.wmmess.business.shimu.bean.DaoSession;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "KONG_ZHI_DIAN_RESBEAN".
*/
public class KongZhiDianResbeanDao extends AbstractDao<KongZhiDianResbean, Long> {

    public static final String TABLENAME = "KONG_ZHI_DIAN_RESBEAN";

    /**
     * Properties of entity KongZhiDianResbean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property KongZhiDianId = new Property(1, Long.class, "kongZhiDianId", false, "kongZhiDianId");
        public final static Property Index = new Property(2, int.class, "index", false, "INDEX");
        public final static Property Record = new Property(3, String.class, "record", false, "RECORD");
    }

    private Query<KongZhiDianResbean> step4Resbean_KongZhiDianResbeansQuery;

    public KongZhiDianResbeanDao(DaoConfig config) {
        super(config);
    }
    
    public KongZhiDianResbeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"KONG_ZHI_DIAN_RESBEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"kongZhiDianId\" INTEGER," + // 1: kongZhiDianId
                "\"INDEX\" INTEGER NOT NULL ," + // 2: index
                "\"RECORD\" TEXT);"); // 3: record
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"KONG_ZHI_DIAN_RESBEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, KongZhiDianResbean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long kongZhiDianId = entity.getKongZhiDianId();
        if (kongZhiDianId != null) {
            stmt.bindLong(2, kongZhiDianId);
        }
        stmt.bindLong(3, entity.getIndex());
 
        String record = entity.getRecord();
        if (record != null) {
            stmt.bindString(4, record);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, KongZhiDianResbean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long kongZhiDianId = entity.getKongZhiDianId();
        if (kongZhiDianId != null) {
            stmt.bindLong(2, kongZhiDianId);
        }
        stmt.bindLong(3, entity.getIndex());
 
        String record = entity.getRecord();
        if (record != null) {
            stmt.bindString(4, record);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public KongZhiDianResbean readEntity(Cursor cursor, int offset) {
        KongZhiDianResbean entity = new KongZhiDianResbean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // kongZhiDianId
            cursor.getInt(offset + 2), // index
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // record
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, KongZhiDianResbean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKongZhiDianId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setIndex(cursor.getInt(offset + 2));
        entity.setRecord(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(KongZhiDianResbean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(KongZhiDianResbean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(KongZhiDianResbean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "kongZhiDianResbeans" to-many relationship of Step4Resbean. */
    public List<KongZhiDianResbean> _queryStep4Resbean_KongZhiDianResbeans(Long kongZhiDianId) {
        synchronized (this) {
            if (step4Resbean_KongZhiDianResbeansQuery == null) {
                QueryBuilder<KongZhiDianResbean> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.KongZhiDianId.eq(null));
                step4Resbean_KongZhiDianResbeansQuery = queryBuilder.build();
            }
        }
        Query<KongZhiDianResbean> query = step4Resbean_KongZhiDianResbeansQuery.forCurrentThread();
        query.setParameter(0, kongZhiDianId);
        return query.list();
    }

}
