package com.weimi.wmmess.business.shimu.bean.step11;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.weimi.wmmess.business.shimu.bean.DaoSession;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STEP11_RESBEAN".
*/
public class Step11ResbeanDao extends AbstractDao<Step11Resbean, Long> {

    public static final String TABLENAME = "STEP11_RESBEAN";

    /**
     * Properties of entity Step11Resbean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Step11Id = new Property(0, Long.class, "step11Id", true, "_id");
        public final static Property CurrentStepIsChecked = new Property(1, boolean.class, "currentStepIsChecked", false, "CURRENT_STEP_IS_CHECKED");
        public final static Property Min = new Property(2, String.class, "min", false, "MIN");
        public final static Property Max = new Property(3, String.class, "max", false, "MAX");
        public final static Property Percent = new Property(4, String.class, "percent", false, "PERCENT");
        public final static Property OkOrNG = new Property(5, int.class, "okOrNG", false, "OK_OR_NG");
        public final static Property Han1 = new Property(6, String.class, "han1", false, "HAN1");
        public final static Property Han2 = new Property(7, String.class, "han2", false, "HAN2");
        public final static Property Han3 = new Property(8, String.class, "han3", false, "HAN3");
        public final static Property Han4 = new Property(9, String.class, "han4", false, "HAN4");
        public final static Property Han5 = new Property(10, String.class, "han5", false, "HAN5");
        public final static Property Han6 = new Property(11, String.class, "han6", false, "HAN6");
        public final static Property Han7 = new Property(12, String.class, "han7", false, "HAN7");
        public final static Property Han8 = new Property(13, String.class, "han8", false, "HAN8");
        public final static Property Han9 = new Property(14, String.class, "han9", false, "HAN9");
        public final static Property Han10 = new Property(15, String.class, "han10", false, "HAN10");
        public final static Property Han11 = new Property(16, String.class, "han11", false, "HAN11");
        public final static Property Han12 = new Property(17, String.class, "han12", false, "HAN12");
        public final static Property Han13 = new Property(18, String.class, "han13", false, "HAN13");
        public final static Property Han14 = new Property(19, String.class, "han14", false, "HAN14");
        public final static Property Han15 = new Property(20, String.class, "han15", false, "HAN15");
        public final static Property Han16 = new Property(21, String.class, "han16", false, "HAN16");
        public final static Property Han17 = new Property(22, String.class, "han17", false, "HAN17");
        public final static Property Han18 = new Property(23, String.class, "han18", false, "HAN18");
        public final static Property Han19 = new Property(24, String.class, "han19", false, "HAN19");
        public final static Property Han20 = new Property(25, String.class, "han20", false, "HAN20");
        public final static Property Han21 = new Property(26, String.class, "han21", false, "HAN21");
        public final static Property Han22 = new Property(27, String.class, "han22", false, "HAN22");
        public final static Property Han23 = new Property(28, String.class, "han23", false, "HAN23");
        public final static Property Han24 = new Property(29, String.class, "han24", false, "HAN24");
        public final static Property Han25 = new Property(30, String.class, "han25", false, "HAN25");
        public final static Property Han26 = new Property(31, String.class, "han26", false, "HAN26");
        public final static Property Han27 = new Property(32, String.class, "han27", false, "HAN27");
        public final static Property Han28 = new Property(33, String.class, "han28", false, "HAN28");
        public final static Property Han29 = new Property(34, String.class, "han29", false, "HAN29");
        public final static Property Han30 = new Property(35, String.class, "han30", false, "HAN30");
        public final static Property BuHan1 = new Property(36, String.class, "buHan1", false, "BU_HAN1");
        public final static Property BuHan2 = new Property(37, String.class, "buHan2", false, "BU_HAN2");
        public final static Property BuHan3 = new Property(38, String.class, "buHan3", false, "BU_HAN3");
        public final static Property BuHan4 = new Property(39, String.class, "buHan4", false, "BU_HAN4");
        public final static Property BuHan5 = new Property(40, String.class, "buHan5", false, "BU_HAN5");
        public final static Property BuHan6 = new Property(41, String.class, "buHan6", false, "BU_HAN6");
        public final static Property BuHan7 = new Property(42, String.class, "buHan7", false, "BU_HAN7");
        public final static Property BuHan8 = new Property(43, String.class, "buHan8", false, "BU_HAN8");
        public final static Property BuHan9 = new Property(44, String.class, "buHan9", false, "BU_HAN9");
        public final static Property BuHan10 = new Property(45, String.class, "buHan10", false, "BU_HAN10");
        public final static Property BuHan11 = new Property(46, String.class, "buHan11", false, "BU_HAN11");
        public final static Property BuHan12 = new Property(47, String.class, "buHan12", false, "BU_HAN12");
        public final static Property BuHan13 = new Property(48, String.class, "buHan13", false, "BU_HAN13");
        public final static Property BuHan14 = new Property(49, String.class, "buHan14", false, "BU_HAN14");
        public final static Property BuHan15 = new Property(50, String.class, "buHan15", false, "BU_HAN15");
        public final static Property BuHan16 = new Property(51, String.class, "buHan16", false, "BU_HAN16");
        public final static Property BuHan17 = new Property(52, String.class, "buHan17", false, "BU_HAN17");
        public final static Property BuHan18 = new Property(53, String.class, "buHan18", false, "BU_HAN18");
        public final static Property BuHan19 = new Property(54, String.class, "buHan19", false, "BU_HAN19");
        public final static Property BuHan20 = new Property(55, String.class, "buHan20", false, "BU_HAN20");
        public final static Property BuHan21 = new Property(56, String.class, "buHan21", false, "BU_HAN21");
        public final static Property BuHan22 = new Property(57, String.class, "buHan22", false, "BU_HAN22");
        public final static Property BuHan23 = new Property(58, String.class, "buHan23", false, "BU_HAN23");
        public final static Property BuHan24 = new Property(59, String.class, "buHan24", false, "BU_HAN24");
        public final static Property BuHan25 = new Property(60, String.class, "buHan25", false, "BU_HAN25");
        public final static Property BuHan26 = new Property(61, String.class, "buHan26", false, "BU_HAN26");
        public final static Property BuHan27 = new Property(62, String.class, "buHan27", false, "BU_HAN27");
        public final static Property BuHan28 = new Property(63, String.class, "buHan28", false, "BU_HAN28");
        public final static Property BuHan29 = new Property(64, String.class, "buHan29", false, "BU_HAN29");
        public final static Property BuHan30 = new Property(65, String.class, "buHan30", false, "BU_HAN30");
    }


    public Step11ResbeanDao(DaoConfig config) {
        super(config);
    }
    
    public Step11ResbeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STEP11_RESBEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: step11Id
                "\"CURRENT_STEP_IS_CHECKED\" INTEGER NOT NULL ," + // 1: currentStepIsChecked
                "\"MIN\" TEXT," + // 2: min
                "\"MAX\" TEXT," + // 3: max
                "\"PERCENT\" TEXT," + // 4: percent
                "\"OK_OR_NG\" INTEGER NOT NULL ," + // 5: okOrNG
                "\"HAN1\" TEXT," + // 6: han1
                "\"HAN2\" TEXT," + // 7: han2
                "\"HAN3\" TEXT," + // 8: han3
                "\"HAN4\" TEXT," + // 9: han4
                "\"HAN5\" TEXT," + // 10: han5
                "\"HAN6\" TEXT," + // 11: han6
                "\"HAN7\" TEXT," + // 12: han7
                "\"HAN8\" TEXT," + // 13: han8
                "\"HAN9\" TEXT," + // 14: han9
                "\"HAN10\" TEXT," + // 15: han10
                "\"HAN11\" TEXT," + // 16: han11
                "\"HAN12\" TEXT," + // 17: han12
                "\"HAN13\" TEXT," + // 18: han13
                "\"HAN14\" TEXT," + // 19: han14
                "\"HAN15\" TEXT," + // 20: han15
                "\"HAN16\" TEXT," + // 21: han16
                "\"HAN17\" TEXT," + // 22: han17
                "\"HAN18\" TEXT," + // 23: han18
                "\"HAN19\" TEXT," + // 24: han19
                "\"HAN20\" TEXT," + // 25: han20
                "\"HAN21\" TEXT," + // 26: han21
                "\"HAN22\" TEXT," + // 27: han22
                "\"HAN23\" TEXT," + // 28: han23
                "\"HAN24\" TEXT," + // 29: han24
                "\"HAN25\" TEXT," + // 30: han25
                "\"HAN26\" TEXT," + // 31: han26
                "\"HAN27\" TEXT," + // 32: han27
                "\"HAN28\" TEXT," + // 33: han28
                "\"HAN29\" TEXT," + // 34: han29
                "\"HAN30\" TEXT," + // 35: han30
                "\"BU_HAN1\" TEXT," + // 36: buHan1
                "\"BU_HAN2\" TEXT," + // 37: buHan2
                "\"BU_HAN3\" TEXT," + // 38: buHan3
                "\"BU_HAN4\" TEXT," + // 39: buHan4
                "\"BU_HAN5\" TEXT," + // 40: buHan5
                "\"BU_HAN6\" TEXT," + // 41: buHan6
                "\"BU_HAN7\" TEXT," + // 42: buHan7
                "\"BU_HAN8\" TEXT," + // 43: buHan8
                "\"BU_HAN9\" TEXT," + // 44: buHan9
                "\"BU_HAN10\" TEXT," + // 45: buHan10
                "\"BU_HAN11\" TEXT," + // 46: buHan11
                "\"BU_HAN12\" TEXT," + // 47: buHan12
                "\"BU_HAN13\" TEXT," + // 48: buHan13
                "\"BU_HAN14\" TEXT," + // 49: buHan14
                "\"BU_HAN15\" TEXT," + // 50: buHan15
                "\"BU_HAN16\" TEXT," + // 51: buHan16
                "\"BU_HAN17\" TEXT," + // 52: buHan17
                "\"BU_HAN18\" TEXT," + // 53: buHan18
                "\"BU_HAN19\" TEXT," + // 54: buHan19
                "\"BU_HAN20\" TEXT," + // 55: buHan20
                "\"BU_HAN21\" TEXT," + // 56: buHan21
                "\"BU_HAN22\" TEXT," + // 57: buHan22
                "\"BU_HAN23\" TEXT," + // 58: buHan23
                "\"BU_HAN24\" TEXT," + // 59: buHan24
                "\"BU_HAN25\" TEXT," + // 60: buHan25
                "\"BU_HAN26\" TEXT," + // 61: buHan26
                "\"BU_HAN27\" TEXT," + // 62: buHan27
                "\"BU_HAN28\" TEXT," + // 63: buHan28
                "\"BU_HAN29\" TEXT," + // 64: buHan29
                "\"BU_HAN30\" TEXT);"); // 65: buHan30
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STEP11_RESBEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Step11Resbean entity) {
        stmt.clearBindings();
 
        Long step11Id = entity.getStep11Id();
        if (step11Id != null) {
            stmt.bindLong(1, step11Id);
        }
        stmt.bindLong(2, entity.getCurrentStepIsChecked() ? 1L: 0L);
 
        String min = entity.getMin();
        if (min != null) {
            stmt.bindString(3, min);
        }
 
        String max = entity.getMax();
        if (max != null) {
            stmt.bindString(4, max);
        }
 
        String percent = entity.getPercent();
        if (percent != null) {
            stmt.bindString(5, percent);
        }
        stmt.bindLong(6, entity.getOkOrNG());
 
        String han1 = entity.getHan1();
        if (han1 != null) {
            stmt.bindString(7, han1);
        }
 
        String han2 = entity.getHan2();
        if (han2 != null) {
            stmt.bindString(8, han2);
        }
 
        String han3 = entity.getHan3();
        if (han3 != null) {
            stmt.bindString(9, han3);
        }
 
        String han4 = entity.getHan4();
        if (han4 != null) {
            stmt.bindString(10, han4);
        }
 
        String han5 = entity.getHan5();
        if (han5 != null) {
            stmt.bindString(11, han5);
        }
 
        String han6 = entity.getHan6();
        if (han6 != null) {
            stmt.bindString(12, han6);
        }
 
        String han7 = entity.getHan7();
        if (han7 != null) {
            stmt.bindString(13, han7);
        }
 
        String han8 = entity.getHan8();
        if (han8 != null) {
            stmt.bindString(14, han8);
        }
 
        String han9 = entity.getHan9();
        if (han9 != null) {
            stmt.bindString(15, han9);
        }
 
        String han10 = entity.getHan10();
        if (han10 != null) {
            stmt.bindString(16, han10);
        }
 
        String han11 = entity.getHan11();
        if (han11 != null) {
            stmt.bindString(17, han11);
        }
 
        String han12 = entity.getHan12();
        if (han12 != null) {
            stmt.bindString(18, han12);
        }
 
        String han13 = entity.getHan13();
        if (han13 != null) {
            stmt.bindString(19, han13);
        }
 
        String han14 = entity.getHan14();
        if (han14 != null) {
            stmt.bindString(20, han14);
        }
 
        String han15 = entity.getHan15();
        if (han15 != null) {
            stmt.bindString(21, han15);
        }
 
        String han16 = entity.getHan16();
        if (han16 != null) {
            stmt.bindString(22, han16);
        }
 
        String han17 = entity.getHan17();
        if (han17 != null) {
            stmt.bindString(23, han17);
        }
 
        String han18 = entity.getHan18();
        if (han18 != null) {
            stmt.bindString(24, han18);
        }
 
        String han19 = entity.getHan19();
        if (han19 != null) {
            stmt.bindString(25, han19);
        }
 
        String han20 = entity.getHan20();
        if (han20 != null) {
            stmt.bindString(26, han20);
        }
 
        String han21 = entity.getHan21();
        if (han21 != null) {
            stmt.bindString(27, han21);
        }
 
        String han22 = entity.getHan22();
        if (han22 != null) {
            stmt.bindString(28, han22);
        }
 
        String han23 = entity.getHan23();
        if (han23 != null) {
            stmt.bindString(29, han23);
        }
 
        String han24 = entity.getHan24();
        if (han24 != null) {
            stmt.bindString(30, han24);
        }
 
        String han25 = entity.getHan25();
        if (han25 != null) {
            stmt.bindString(31, han25);
        }
 
        String han26 = entity.getHan26();
        if (han26 != null) {
            stmt.bindString(32, han26);
        }
 
        String han27 = entity.getHan27();
        if (han27 != null) {
            stmt.bindString(33, han27);
        }
 
        String han28 = entity.getHan28();
        if (han28 != null) {
            stmt.bindString(34, han28);
        }
 
        String han29 = entity.getHan29();
        if (han29 != null) {
            stmt.bindString(35, han29);
        }
 
        String han30 = entity.getHan30();
        if (han30 != null) {
            stmt.bindString(36, han30);
        }
 
        String buHan1 = entity.getBuHan1();
        if (buHan1 != null) {
            stmt.bindString(37, buHan1);
        }
 
        String buHan2 = entity.getBuHan2();
        if (buHan2 != null) {
            stmt.bindString(38, buHan2);
        }
 
        String buHan3 = entity.getBuHan3();
        if (buHan3 != null) {
            stmt.bindString(39, buHan3);
        }
 
        String buHan4 = entity.getBuHan4();
        if (buHan4 != null) {
            stmt.bindString(40, buHan4);
        }
 
        String buHan5 = entity.getBuHan5();
        if (buHan5 != null) {
            stmt.bindString(41, buHan5);
        }
 
        String buHan6 = entity.getBuHan6();
        if (buHan6 != null) {
            stmt.bindString(42, buHan6);
        }
 
        String buHan7 = entity.getBuHan7();
        if (buHan7 != null) {
            stmt.bindString(43, buHan7);
        }
 
        String buHan8 = entity.getBuHan8();
        if (buHan8 != null) {
            stmt.bindString(44, buHan8);
        }
 
        String buHan9 = entity.getBuHan9();
        if (buHan9 != null) {
            stmt.bindString(45, buHan9);
        }
 
        String buHan10 = entity.getBuHan10();
        if (buHan10 != null) {
            stmt.bindString(46, buHan10);
        }
 
        String buHan11 = entity.getBuHan11();
        if (buHan11 != null) {
            stmt.bindString(47, buHan11);
        }
 
        String buHan12 = entity.getBuHan12();
        if (buHan12 != null) {
            stmt.bindString(48, buHan12);
        }
 
        String buHan13 = entity.getBuHan13();
        if (buHan13 != null) {
            stmt.bindString(49, buHan13);
        }
 
        String buHan14 = entity.getBuHan14();
        if (buHan14 != null) {
            stmt.bindString(50, buHan14);
        }
 
        String buHan15 = entity.getBuHan15();
        if (buHan15 != null) {
            stmt.bindString(51, buHan15);
        }
 
        String buHan16 = entity.getBuHan16();
        if (buHan16 != null) {
            stmt.bindString(52, buHan16);
        }
 
        String buHan17 = entity.getBuHan17();
        if (buHan17 != null) {
            stmt.bindString(53, buHan17);
        }
 
        String buHan18 = entity.getBuHan18();
        if (buHan18 != null) {
            stmt.bindString(54, buHan18);
        }
 
        String buHan19 = entity.getBuHan19();
        if (buHan19 != null) {
            stmt.bindString(55, buHan19);
        }
 
        String buHan20 = entity.getBuHan20();
        if (buHan20 != null) {
            stmt.bindString(56, buHan20);
        }
 
        String buHan21 = entity.getBuHan21();
        if (buHan21 != null) {
            stmt.bindString(57, buHan21);
        }
 
        String buHan22 = entity.getBuHan22();
        if (buHan22 != null) {
            stmt.bindString(58, buHan22);
        }
 
        String buHan23 = entity.getBuHan23();
        if (buHan23 != null) {
            stmt.bindString(59, buHan23);
        }
 
        String buHan24 = entity.getBuHan24();
        if (buHan24 != null) {
            stmt.bindString(60, buHan24);
        }
 
        String buHan25 = entity.getBuHan25();
        if (buHan25 != null) {
            stmt.bindString(61, buHan25);
        }
 
        String buHan26 = entity.getBuHan26();
        if (buHan26 != null) {
            stmt.bindString(62, buHan26);
        }
 
        String buHan27 = entity.getBuHan27();
        if (buHan27 != null) {
            stmt.bindString(63, buHan27);
        }
 
        String buHan28 = entity.getBuHan28();
        if (buHan28 != null) {
            stmt.bindString(64, buHan28);
        }
 
        String buHan29 = entity.getBuHan29();
        if (buHan29 != null) {
            stmt.bindString(65, buHan29);
        }
 
        String buHan30 = entity.getBuHan30();
        if (buHan30 != null) {
            stmt.bindString(66, buHan30);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Step11Resbean entity) {
        stmt.clearBindings();
 
        Long step11Id = entity.getStep11Id();
        if (step11Id != null) {
            stmt.bindLong(1, step11Id);
        }
        stmt.bindLong(2, entity.getCurrentStepIsChecked() ? 1L: 0L);
 
        String min = entity.getMin();
        if (min != null) {
            stmt.bindString(3, min);
        }
 
        String max = entity.getMax();
        if (max != null) {
            stmt.bindString(4, max);
        }
 
        String percent = entity.getPercent();
        if (percent != null) {
            stmt.bindString(5, percent);
        }
        stmt.bindLong(6, entity.getOkOrNG());
 
        String han1 = entity.getHan1();
        if (han1 != null) {
            stmt.bindString(7, han1);
        }
 
        String han2 = entity.getHan2();
        if (han2 != null) {
            stmt.bindString(8, han2);
        }
 
        String han3 = entity.getHan3();
        if (han3 != null) {
            stmt.bindString(9, han3);
        }
 
        String han4 = entity.getHan4();
        if (han4 != null) {
            stmt.bindString(10, han4);
        }
 
        String han5 = entity.getHan5();
        if (han5 != null) {
            stmt.bindString(11, han5);
        }
 
        String han6 = entity.getHan6();
        if (han6 != null) {
            stmt.bindString(12, han6);
        }
 
        String han7 = entity.getHan7();
        if (han7 != null) {
            stmt.bindString(13, han7);
        }
 
        String han8 = entity.getHan8();
        if (han8 != null) {
            stmt.bindString(14, han8);
        }
 
        String han9 = entity.getHan9();
        if (han9 != null) {
            stmt.bindString(15, han9);
        }
 
        String han10 = entity.getHan10();
        if (han10 != null) {
            stmt.bindString(16, han10);
        }
 
        String han11 = entity.getHan11();
        if (han11 != null) {
            stmt.bindString(17, han11);
        }
 
        String han12 = entity.getHan12();
        if (han12 != null) {
            stmt.bindString(18, han12);
        }
 
        String han13 = entity.getHan13();
        if (han13 != null) {
            stmt.bindString(19, han13);
        }
 
        String han14 = entity.getHan14();
        if (han14 != null) {
            stmt.bindString(20, han14);
        }
 
        String han15 = entity.getHan15();
        if (han15 != null) {
            stmt.bindString(21, han15);
        }
 
        String han16 = entity.getHan16();
        if (han16 != null) {
            stmt.bindString(22, han16);
        }
 
        String han17 = entity.getHan17();
        if (han17 != null) {
            stmt.bindString(23, han17);
        }
 
        String han18 = entity.getHan18();
        if (han18 != null) {
            stmt.bindString(24, han18);
        }
 
        String han19 = entity.getHan19();
        if (han19 != null) {
            stmt.bindString(25, han19);
        }
 
        String han20 = entity.getHan20();
        if (han20 != null) {
            stmt.bindString(26, han20);
        }
 
        String han21 = entity.getHan21();
        if (han21 != null) {
            stmt.bindString(27, han21);
        }
 
        String han22 = entity.getHan22();
        if (han22 != null) {
            stmt.bindString(28, han22);
        }
 
        String han23 = entity.getHan23();
        if (han23 != null) {
            stmt.bindString(29, han23);
        }
 
        String han24 = entity.getHan24();
        if (han24 != null) {
            stmt.bindString(30, han24);
        }
 
        String han25 = entity.getHan25();
        if (han25 != null) {
            stmt.bindString(31, han25);
        }
 
        String han26 = entity.getHan26();
        if (han26 != null) {
            stmt.bindString(32, han26);
        }
 
        String han27 = entity.getHan27();
        if (han27 != null) {
            stmt.bindString(33, han27);
        }
 
        String han28 = entity.getHan28();
        if (han28 != null) {
            stmt.bindString(34, han28);
        }
 
        String han29 = entity.getHan29();
        if (han29 != null) {
            stmt.bindString(35, han29);
        }
 
        String han30 = entity.getHan30();
        if (han30 != null) {
            stmt.bindString(36, han30);
        }
 
        String buHan1 = entity.getBuHan1();
        if (buHan1 != null) {
            stmt.bindString(37, buHan1);
        }
 
        String buHan2 = entity.getBuHan2();
        if (buHan2 != null) {
            stmt.bindString(38, buHan2);
        }
 
        String buHan3 = entity.getBuHan3();
        if (buHan3 != null) {
            stmt.bindString(39, buHan3);
        }
 
        String buHan4 = entity.getBuHan4();
        if (buHan4 != null) {
            stmt.bindString(40, buHan4);
        }
 
        String buHan5 = entity.getBuHan5();
        if (buHan5 != null) {
            stmt.bindString(41, buHan5);
        }
 
        String buHan6 = entity.getBuHan6();
        if (buHan6 != null) {
            stmt.bindString(42, buHan6);
        }
 
        String buHan7 = entity.getBuHan7();
        if (buHan7 != null) {
            stmt.bindString(43, buHan7);
        }
 
        String buHan8 = entity.getBuHan8();
        if (buHan8 != null) {
            stmt.bindString(44, buHan8);
        }
 
        String buHan9 = entity.getBuHan9();
        if (buHan9 != null) {
            stmt.bindString(45, buHan9);
        }
 
        String buHan10 = entity.getBuHan10();
        if (buHan10 != null) {
            stmt.bindString(46, buHan10);
        }
 
        String buHan11 = entity.getBuHan11();
        if (buHan11 != null) {
            stmt.bindString(47, buHan11);
        }
 
        String buHan12 = entity.getBuHan12();
        if (buHan12 != null) {
            stmt.bindString(48, buHan12);
        }
 
        String buHan13 = entity.getBuHan13();
        if (buHan13 != null) {
            stmt.bindString(49, buHan13);
        }
 
        String buHan14 = entity.getBuHan14();
        if (buHan14 != null) {
            stmt.bindString(50, buHan14);
        }
 
        String buHan15 = entity.getBuHan15();
        if (buHan15 != null) {
            stmt.bindString(51, buHan15);
        }
 
        String buHan16 = entity.getBuHan16();
        if (buHan16 != null) {
            stmt.bindString(52, buHan16);
        }
 
        String buHan17 = entity.getBuHan17();
        if (buHan17 != null) {
            stmt.bindString(53, buHan17);
        }
 
        String buHan18 = entity.getBuHan18();
        if (buHan18 != null) {
            stmt.bindString(54, buHan18);
        }
 
        String buHan19 = entity.getBuHan19();
        if (buHan19 != null) {
            stmt.bindString(55, buHan19);
        }
 
        String buHan20 = entity.getBuHan20();
        if (buHan20 != null) {
            stmt.bindString(56, buHan20);
        }
 
        String buHan21 = entity.getBuHan21();
        if (buHan21 != null) {
            stmt.bindString(57, buHan21);
        }
 
        String buHan22 = entity.getBuHan22();
        if (buHan22 != null) {
            stmt.bindString(58, buHan22);
        }
 
        String buHan23 = entity.getBuHan23();
        if (buHan23 != null) {
            stmt.bindString(59, buHan23);
        }
 
        String buHan24 = entity.getBuHan24();
        if (buHan24 != null) {
            stmt.bindString(60, buHan24);
        }
 
        String buHan25 = entity.getBuHan25();
        if (buHan25 != null) {
            stmt.bindString(61, buHan25);
        }
 
        String buHan26 = entity.getBuHan26();
        if (buHan26 != null) {
            stmt.bindString(62, buHan26);
        }
 
        String buHan27 = entity.getBuHan27();
        if (buHan27 != null) {
            stmt.bindString(63, buHan27);
        }
 
        String buHan28 = entity.getBuHan28();
        if (buHan28 != null) {
            stmt.bindString(64, buHan28);
        }
 
        String buHan29 = entity.getBuHan29();
        if (buHan29 != null) {
            stmt.bindString(65, buHan29);
        }
 
        String buHan30 = entity.getBuHan30();
        if (buHan30 != null) {
            stmt.bindString(66, buHan30);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Step11Resbean readEntity(Cursor cursor, int offset) {
        Step11Resbean entity = new Step11Resbean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // step11Id
            cursor.getShort(offset + 1) != 0, // currentStepIsChecked
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // min
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // max
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // percent
            cursor.getInt(offset + 5), // okOrNG
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // han1
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // han2
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // han3
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // han4
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // han5
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // han6
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // han7
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // han8
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // han9
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // han10
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // han11
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // han12
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // han13
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // han14
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // han15
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // han16
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // han17
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // han18
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // han19
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // han20
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // han21
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // han22
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // han23
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // han24
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // han25
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // han26
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // han27
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // han28
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // han29
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // han30
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // buHan1
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // buHan2
            cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38), // buHan3
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // buHan4
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // buHan5
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41), // buHan6
            cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42), // buHan7
            cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43), // buHan8
            cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44), // buHan9
            cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45), // buHan10
            cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46), // buHan11
            cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47), // buHan12
            cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48), // buHan13
            cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49), // buHan14
            cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50), // buHan15
            cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51), // buHan16
            cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52), // buHan17
            cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53), // buHan18
            cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54), // buHan19
            cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55), // buHan20
            cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56), // buHan21
            cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57), // buHan22
            cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58), // buHan23
            cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59), // buHan24
            cursor.isNull(offset + 60) ? null : cursor.getString(offset + 60), // buHan25
            cursor.isNull(offset + 61) ? null : cursor.getString(offset + 61), // buHan26
            cursor.isNull(offset + 62) ? null : cursor.getString(offset + 62), // buHan27
            cursor.isNull(offset + 63) ? null : cursor.getString(offset + 63), // buHan28
            cursor.isNull(offset + 64) ? null : cursor.getString(offset + 64), // buHan29
            cursor.isNull(offset + 65) ? null : cursor.getString(offset + 65) // buHan30
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Step11Resbean entity, int offset) {
        entity.setStep11Id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCurrentStepIsChecked(cursor.getShort(offset + 1) != 0);
        entity.setMin(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMax(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPercent(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setOkOrNG(cursor.getInt(offset + 5));
        entity.setHan1(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setHan2(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setHan3(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setHan4(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setHan5(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setHan6(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setHan7(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setHan8(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setHan9(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setHan10(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setHan11(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setHan12(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setHan13(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setHan14(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setHan15(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setHan16(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setHan17(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setHan18(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setHan19(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setHan20(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setHan21(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setHan22(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setHan23(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setHan24(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setHan25(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setHan26(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setHan27(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setHan28(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setHan29(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setHan30(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setBuHan1(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setBuHan2(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setBuHan3(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setBuHan4(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setBuHan5(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setBuHan6(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
        entity.setBuHan7(cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42));
        entity.setBuHan8(cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43));
        entity.setBuHan9(cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44));
        entity.setBuHan10(cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45));
        entity.setBuHan11(cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46));
        entity.setBuHan12(cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47));
        entity.setBuHan13(cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48));
        entity.setBuHan14(cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49));
        entity.setBuHan15(cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50));
        entity.setBuHan16(cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51));
        entity.setBuHan17(cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52));
        entity.setBuHan18(cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53));
        entity.setBuHan19(cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54));
        entity.setBuHan20(cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55));
        entity.setBuHan21(cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56));
        entity.setBuHan22(cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57));
        entity.setBuHan23(cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58));
        entity.setBuHan24(cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59));
        entity.setBuHan25(cursor.isNull(offset + 60) ? null : cursor.getString(offset + 60));
        entity.setBuHan26(cursor.isNull(offset + 61) ? null : cursor.getString(offset + 61));
        entity.setBuHan27(cursor.isNull(offset + 62) ? null : cursor.getString(offset + 62));
        entity.setBuHan28(cursor.isNull(offset + 63) ? null : cursor.getString(offset + 63));
        entity.setBuHan29(cursor.isNull(offset + 64) ? null : cursor.getString(offset + 64));
        entity.setBuHan30(cursor.isNull(offset + 65) ? null : cursor.getString(offset + 65));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Step11Resbean entity, long rowId) {
        entity.setStep11Id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Step11Resbean entity) {
        if(entity != null) {
            return entity.getStep11Id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Step11Resbean entity) {
        return entity.getStep11Id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
