package com.weimi.wmmess.business.shimu.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HEAD_INFO_RESBEAN".
*/
public class HeadInfoResbeanDao extends AbstractDao<HeadInfoResbean, Long> {

    public static final String TABLENAME = "HEAD_INFO_RESBEAN";

    /**
     * Properties of entity HeadInfoResbean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property HeadInfoId = new Property(0, Long.class, "headInfoId", true, "_id");
        public final static Property Date = new Property(1, String.class, "date", false, "DATE");
        public final static Property MujuBianHao = new Property(2, String.class, "mujuBianHao", false, "MUJU_BIAN_HAO");
        public final static Property XiangmuBianHao = new Property(3, String.class, "xiangmuBianHao", false, "XIANGMU_BIAN_HAO");
        public final static Property LiuDaoLeiXing = new Property(4, String.class, "liuDaoLeiXing", false, "LIU_DAO_LEI_XING");
        public final static Property JiQiBianHao = new Property(5, String.class, "jiQiBianHao", false, "JI_QI_BIAN_HAO");
        public final static Property JiQiDunWei = new Property(6, String.class, "jiQiDunWei", false, "JI_QI_DUN_WEI");
        public final static Property LuoGanZhiJing = new Property(7, String.class, "luoGanZhiJing", false, "LUO_GAN_ZHI_JING");
        public final static Property SheZuiZhiJing = new Property(8, String.class, "sheZuiZhiJing", false, "SHE_ZUI_ZHI_JING");
        public final static Property ChanPinMingCheng = new Property(9, String.class, "chanPinMingCheng", false, "CHAN_PIN_MING_CHENG");
        public final static Property ChanPinBianHao = new Property(10, String.class, "chanPinBianHao", false, "CHAN_PIN_BIAN_HAO");
        public final static Property KeHuLiaoHao = new Property(11, String.class, "keHuLiaoHao", false, "KE_HU_LIAO_HAO");
        public final static Property ChanPinBanBen = new Property(12, String.class, "chanPinBanBen", false, "CHAN_PIN_BAN_BEN");
        public final static Property YuanLiaoMingCheng = new Property(13, String.class, "yuanLiaoMingCheng", false, "YUAN_LIAO_MING_CHENG");
        public final static Property YuanLiaoLiaoHao = new Property(14, String.class, "yuanLiaoLiaoHao", false, "YUAN_LIAO_LIAO_HAO");
        public final static Property YuanLiaoGongYingShang = new Property(15, String.class, "yuanLiaoGongYingShang", false, "YUAN_LIAO_GONG_YING_SHANG");
        public final static Property RLDJRDS = new Property(16, String.class, "RLDJRDS", false, "RLDJRDS");
        public final static Property GanZaoWenDu = new Property(17, String.class, "ganZaoWenDu", false, "GAN_ZAO_WEN_DU");
        public final static Property GanZaoShiJian = new Property(18, String.class, "ganZaoShiJian", false, "GAN_ZAO_SHI_JIAN");
        public final static Property YuanLiaoHanShuiFen = new Property(19, String.class, "yuanLiaoHanShuiFen", false, "YUAN_LIAO_HAN_SHUI_FEN");
        public final static Property ChengXingWenDu = new Property(20, String.class, "chengXingWenDu", false, "CHENG_XING_WEN_DU");
        public final static Property MuJuWenDu = new Property(21, String.class, "muJuWenDu", false, "MU_JU_WEN_DU");
        public final static Property SheChuYaLi = new Property(22, String.class, "sheChuYaLi", false, "SHE_CHU_YA_LI");
        public final static Property SheChuShiJian = new Property(23, String.class, "sheChuShiJian", false, "SHE_CHU_SHI_JIAN");
        public final static Property SheChuSuDu = new Property(24, String.class, "sheChuSuDu", false, "SHE_CHU_SU_DU");
        public final static Property BaoYaYaLi = new Property(25, String.class, "baoYaYaLi", false, "BAO_YA_YA_LI");
        public final static Property BaoYaShiJian = new Property(26, String.class, "baoYaShiJian", false, "BAO_YA_SHI_JIAN");
        public final static Property SuoMuLi = new Property(27, String.class, "suoMuLi", false, "SUO_MU_LI");
        public final static Property KaiHeMuShiJian = new Property(28, String.class, "kaiHeMuShiJian", false, "KAI_HE_MU_SHI_JIAN");
        public final static Property LengQueShiJian = new Property(29, String.class, "lengQueShiJian", false, "LENG_QUE_SHI_JIAN");
        public final static Property LuoGanSuDu = new Property(30, String.class, "luoGanSuDu", false, "LUO_GAN_SU_DU");
        public final static Property DingTuiChuShiJian = new Property(31, String.class, "dingTuiChuShiJian", false, "DING_TUI_CHU_SHI_JIAN");
        public final static Property BeiYa = new Property(32, String.class, "beiYa", false, "BEI_YA");
    }


    public HeadInfoResbeanDao(DaoConfig config) {
        super(config);
    }
    
    public HeadInfoResbeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HEAD_INFO_RESBEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: headInfoId
                "\"DATE\" TEXT," + // 1: date
                "\"MUJU_BIAN_HAO\" TEXT," + // 2: mujuBianHao
                "\"XIANGMU_BIAN_HAO\" TEXT," + // 3: xiangmuBianHao
                "\"LIU_DAO_LEI_XING\" TEXT," + // 4: liuDaoLeiXing
                "\"JI_QI_BIAN_HAO\" TEXT," + // 5: jiQiBianHao
                "\"JI_QI_DUN_WEI\" TEXT," + // 6: jiQiDunWei
                "\"LUO_GAN_ZHI_JING\" TEXT," + // 7: luoGanZhiJing
                "\"SHE_ZUI_ZHI_JING\" TEXT," + // 8: sheZuiZhiJing
                "\"CHAN_PIN_MING_CHENG\" TEXT," + // 9: chanPinMingCheng
                "\"CHAN_PIN_BIAN_HAO\" TEXT," + // 10: chanPinBianHao
                "\"KE_HU_LIAO_HAO\" TEXT," + // 11: keHuLiaoHao
                "\"CHAN_PIN_BAN_BEN\" TEXT," + // 12: chanPinBanBen
                "\"YUAN_LIAO_MING_CHENG\" TEXT," + // 13: yuanLiaoMingCheng
                "\"YUAN_LIAO_LIAO_HAO\" TEXT," + // 14: yuanLiaoLiaoHao
                "\"YUAN_LIAO_GONG_YING_SHANG\" TEXT," + // 15: yuanLiaoGongYingShang
                "\"RLDJRDS\" TEXT," + // 16: RLDJRDS
                "\"GAN_ZAO_WEN_DU\" TEXT," + // 17: ganZaoWenDu
                "\"GAN_ZAO_SHI_JIAN\" TEXT," + // 18: ganZaoShiJian
                "\"YUAN_LIAO_HAN_SHUI_FEN\" TEXT," + // 19: yuanLiaoHanShuiFen
                "\"CHENG_XING_WEN_DU\" TEXT," + // 20: chengXingWenDu
                "\"MU_JU_WEN_DU\" TEXT," + // 21: muJuWenDu
                "\"SHE_CHU_YA_LI\" TEXT," + // 22: sheChuYaLi
                "\"SHE_CHU_SHI_JIAN\" TEXT," + // 23: sheChuShiJian
                "\"SHE_CHU_SU_DU\" TEXT," + // 24: sheChuSuDu
                "\"BAO_YA_YA_LI\" TEXT," + // 25: baoYaYaLi
                "\"BAO_YA_SHI_JIAN\" TEXT," + // 26: baoYaShiJian
                "\"SUO_MU_LI\" TEXT," + // 27: suoMuLi
                "\"KAI_HE_MU_SHI_JIAN\" TEXT," + // 28: kaiHeMuShiJian
                "\"LENG_QUE_SHI_JIAN\" TEXT," + // 29: lengQueShiJian
                "\"LUO_GAN_SU_DU\" TEXT," + // 30: luoGanSuDu
                "\"DING_TUI_CHU_SHI_JIAN\" TEXT," + // 31: dingTuiChuShiJian
                "\"BEI_YA\" TEXT);"); // 32: beiYa
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HEAD_INFO_RESBEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HeadInfoResbean entity) {
        stmt.clearBindings();
 
        Long headInfoId = entity.getHeadInfoId();
        if (headInfoId != null) {
            stmt.bindLong(1, headInfoId);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(2, date);
        }
 
        String mujuBianHao = entity.getMujuBianHao();
        if (mujuBianHao != null) {
            stmt.bindString(3, mujuBianHao);
        }
 
        String xiangmuBianHao = entity.getXiangmuBianHao();
        if (xiangmuBianHao != null) {
            stmt.bindString(4, xiangmuBianHao);
        }
 
        String liuDaoLeiXing = entity.getLiuDaoLeiXing();
        if (liuDaoLeiXing != null) {
            stmt.bindString(5, liuDaoLeiXing);
        }
 
        String jiQiBianHao = entity.getJiQiBianHao();
        if (jiQiBianHao != null) {
            stmt.bindString(6, jiQiBianHao);
        }
 
        String jiQiDunWei = entity.getJiQiDunWei();
        if (jiQiDunWei != null) {
            stmt.bindString(7, jiQiDunWei);
        }
 
        String luoGanZhiJing = entity.getLuoGanZhiJing();
        if (luoGanZhiJing != null) {
            stmt.bindString(8, luoGanZhiJing);
        }
 
        String sheZuiZhiJing = entity.getSheZuiZhiJing();
        if (sheZuiZhiJing != null) {
            stmt.bindString(9, sheZuiZhiJing);
        }
 
        String chanPinMingCheng = entity.getChanPinMingCheng();
        if (chanPinMingCheng != null) {
            stmt.bindString(10, chanPinMingCheng);
        }
 
        String chanPinBianHao = entity.getChanPinBianHao();
        if (chanPinBianHao != null) {
            stmt.bindString(11, chanPinBianHao);
        }
 
        String keHuLiaoHao = entity.getKeHuLiaoHao();
        if (keHuLiaoHao != null) {
            stmt.bindString(12, keHuLiaoHao);
        }
 
        String chanPinBanBen = entity.getChanPinBanBen();
        if (chanPinBanBen != null) {
            stmt.bindString(13, chanPinBanBen);
        }
 
        String yuanLiaoMingCheng = entity.getYuanLiaoMingCheng();
        if (yuanLiaoMingCheng != null) {
            stmt.bindString(14, yuanLiaoMingCheng);
        }
 
        String yuanLiaoLiaoHao = entity.getYuanLiaoLiaoHao();
        if (yuanLiaoLiaoHao != null) {
            stmt.bindString(15, yuanLiaoLiaoHao);
        }
 
        String yuanLiaoGongYingShang = entity.getYuanLiaoGongYingShang();
        if (yuanLiaoGongYingShang != null) {
            stmt.bindString(16, yuanLiaoGongYingShang);
        }
 
        String RLDJRDS = entity.getRLDJRDS();
        if (RLDJRDS != null) {
            stmt.bindString(17, RLDJRDS);
        }
 
        String ganZaoWenDu = entity.getGanZaoWenDu();
        if (ganZaoWenDu != null) {
            stmt.bindString(18, ganZaoWenDu);
        }
 
        String ganZaoShiJian = entity.getGanZaoShiJian();
        if (ganZaoShiJian != null) {
            stmt.bindString(19, ganZaoShiJian);
        }
 
        String yuanLiaoHanShuiFen = entity.getYuanLiaoHanShuiFen();
        if (yuanLiaoHanShuiFen != null) {
            stmt.bindString(20, yuanLiaoHanShuiFen);
        }
 
        String chengXingWenDu = entity.getChengXingWenDu();
        if (chengXingWenDu != null) {
            stmt.bindString(21, chengXingWenDu);
        }
 
        String muJuWenDu = entity.getMuJuWenDu();
        if (muJuWenDu != null) {
            stmt.bindString(22, muJuWenDu);
        }
 
        String sheChuYaLi = entity.getSheChuYaLi();
        if (sheChuYaLi != null) {
            stmt.bindString(23, sheChuYaLi);
        }
 
        String sheChuShiJian = entity.getSheChuShiJian();
        if (sheChuShiJian != null) {
            stmt.bindString(24, sheChuShiJian);
        }
 
        String sheChuSuDu = entity.getSheChuSuDu();
        if (sheChuSuDu != null) {
            stmt.bindString(25, sheChuSuDu);
        }
 
        String baoYaYaLi = entity.getBaoYaYaLi();
        if (baoYaYaLi != null) {
            stmt.bindString(26, baoYaYaLi);
        }
 
        String baoYaShiJian = entity.getBaoYaShiJian();
        if (baoYaShiJian != null) {
            stmt.bindString(27, baoYaShiJian);
        }
 
        String suoMuLi = entity.getSuoMuLi();
        if (suoMuLi != null) {
            stmt.bindString(28, suoMuLi);
        }
 
        String kaiHeMuShiJian = entity.getKaiHeMuShiJian();
        if (kaiHeMuShiJian != null) {
            stmt.bindString(29, kaiHeMuShiJian);
        }
 
        String lengQueShiJian = entity.getLengQueShiJian();
        if (lengQueShiJian != null) {
            stmt.bindString(30, lengQueShiJian);
        }
 
        String luoGanSuDu = entity.getLuoGanSuDu();
        if (luoGanSuDu != null) {
            stmt.bindString(31, luoGanSuDu);
        }
 
        String dingTuiChuShiJian = entity.getDingTuiChuShiJian();
        if (dingTuiChuShiJian != null) {
            stmt.bindString(32, dingTuiChuShiJian);
        }
 
        String beiYa = entity.getBeiYa();
        if (beiYa != null) {
            stmt.bindString(33, beiYa);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HeadInfoResbean entity) {
        stmt.clearBindings();
 
        Long headInfoId = entity.getHeadInfoId();
        if (headInfoId != null) {
            stmt.bindLong(1, headInfoId);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(2, date);
        }
 
        String mujuBianHao = entity.getMujuBianHao();
        if (mujuBianHao != null) {
            stmt.bindString(3, mujuBianHao);
        }
 
        String xiangmuBianHao = entity.getXiangmuBianHao();
        if (xiangmuBianHao != null) {
            stmt.bindString(4, xiangmuBianHao);
        }
 
        String liuDaoLeiXing = entity.getLiuDaoLeiXing();
        if (liuDaoLeiXing != null) {
            stmt.bindString(5, liuDaoLeiXing);
        }
 
        String jiQiBianHao = entity.getJiQiBianHao();
        if (jiQiBianHao != null) {
            stmt.bindString(6, jiQiBianHao);
        }
 
        String jiQiDunWei = entity.getJiQiDunWei();
        if (jiQiDunWei != null) {
            stmt.bindString(7, jiQiDunWei);
        }
 
        String luoGanZhiJing = entity.getLuoGanZhiJing();
        if (luoGanZhiJing != null) {
            stmt.bindString(8, luoGanZhiJing);
        }
 
        String sheZuiZhiJing = entity.getSheZuiZhiJing();
        if (sheZuiZhiJing != null) {
            stmt.bindString(9, sheZuiZhiJing);
        }
 
        String chanPinMingCheng = entity.getChanPinMingCheng();
        if (chanPinMingCheng != null) {
            stmt.bindString(10, chanPinMingCheng);
        }
 
        String chanPinBianHao = entity.getChanPinBianHao();
        if (chanPinBianHao != null) {
            stmt.bindString(11, chanPinBianHao);
        }
 
        String keHuLiaoHao = entity.getKeHuLiaoHao();
        if (keHuLiaoHao != null) {
            stmt.bindString(12, keHuLiaoHao);
        }
 
        String chanPinBanBen = entity.getChanPinBanBen();
        if (chanPinBanBen != null) {
            stmt.bindString(13, chanPinBanBen);
        }
 
        String yuanLiaoMingCheng = entity.getYuanLiaoMingCheng();
        if (yuanLiaoMingCheng != null) {
            stmt.bindString(14, yuanLiaoMingCheng);
        }
 
        String yuanLiaoLiaoHao = entity.getYuanLiaoLiaoHao();
        if (yuanLiaoLiaoHao != null) {
            stmt.bindString(15, yuanLiaoLiaoHao);
        }
 
        String yuanLiaoGongYingShang = entity.getYuanLiaoGongYingShang();
        if (yuanLiaoGongYingShang != null) {
            stmt.bindString(16, yuanLiaoGongYingShang);
        }
 
        String RLDJRDS = entity.getRLDJRDS();
        if (RLDJRDS != null) {
            stmt.bindString(17, RLDJRDS);
        }
 
        String ganZaoWenDu = entity.getGanZaoWenDu();
        if (ganZaoWenDu != null) {
            stmt.bindString(18, ganZaoWenDu);
        }
 
        String ganZaoShiJian = entity.getGanZaoShiJian();
        if (ganZaoShiJian != null) {
            stmt.bindString(19, ganZaoShiJian);
        }
 
        String yuanLiaoHanShuiFen = entity.getYuanLiaoHanShuiFen();
        if (yuanLiaoHanShuiFen != null) {
            stmt.bindString(20, yuanLiaoHanShuiFen);
        }
 
        String chengXingWenDu = entity.getChengXingWenDu();
        if (chengXingWenDu != null) {
            stmt.bindString(21, chengXingWenDu);
        }
 
        String muJuWenDu = entity.getMuJuWenDu();
        if (muJuWenDu != null) {
            stmt.bindString(22, muJuWenDu);
        }
 
        String sheChuYaLi = entity.getSheChuYaLi();
        if (sheChuYaLi != null) {
            stmt.bindString(23, sheChuYaLi);
        }
 
        String sheChuShiJian = entity.getSheChuShiJian();
        if (sheChuShiJian != null) {
            stmt.bindString(24, sheChuShiJian);
        }
 
        String sheChuSuDu = entity.getSheChuSuDu();
        if (sheChuSuDu != null) {
            stmt.bindString(25, sheChuSuDu);
        }
 
        String baoYaYaLi = entity.getBaoYaYaLi();
        if (baoYaYaLi != null) {
            stmt.bindString(26, baoYaYaLi);
        }
 
        String baoYaShiJian = entity.getBaoYaShiJian();
        if (baoYaShiJian != null) {
            stmt.bindString(27, baoYaShiJian);
        }
 
        String suoMuLi = entity.getSuoMuLi();
        if (suoMuLi != null) {
            stmt.bindString(28, suoMuLi);
        }
 
        String kaiHeMuShiJian = entity.getKaiHeMuShiJian();
        if (kaiHeMuShiJian != null) {
            stmt.bindString(29, kaiHeMuShiJian);
        }
 
        String lengQueShiJian = entity.getLengQueShiJian();
        if (lengQueShiJian != null) {
            stmt.bindString(30, lengQueShiJian);
        }
 
        String luoGanSuDu = entity.getLuoGanSuDu();
        if (luoGanSuDu != null) {
            stmt.bindString(31, luoGanSuDu);
        }
 
        String dingTuiChuShiJian = entity.getDingTuiChuShiJian();
        if (dingTuiChuShiJian != null) {
            stmt.bindString(32, dingTuiChuShiJian);
        }
 
        String beiYa = entity.getBeiYa();
        if (beiYa != null) {
            stmt.bindString(33, beiYa);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HeadInfoResbean readEntity(Cursor cursor, int offset) {
        HeadInfoResbean entity = new HeadInfoResbean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // headInfoId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // date
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // mujuBianHao
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // xiangmuBianHao
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // liuDaoLeiXing
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // jiQiBianHao
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // jiQiDunWei
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // luoGanZhiJing
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // sheZuiZhiJing
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // chanPinMingCheng
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // chanPinBianHao
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // keHuLiaoHao
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // chanPinBanBen
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // yuanLiaoMingCheng
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // yuanLiaoLiaoHao
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // yuanLiaoGongYingShang
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // RLDJRDS
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // ganZaoWenDu
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // ganZaoShiJian
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // yuanLiaoHanShuiFen
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // chengXingWenDu
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // muJuWenDu
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // sheChuYaLi
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // sheChuShiJian
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // sheChuSuDu
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // baoYaYaLi
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // baoYaShiJian
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // suoMuLi
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // kaiHeMuShiJian
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // lengQueShiJian
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // luoGanSuDu
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // dingTuiChuShiJian
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32) // beiYa
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HeadInfoResbean entity, int offset) {
        entity.setHeadInfoId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDate(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMujuBianHao(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setXiangmuBianHao(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLiuDaoLeiXing(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setJiQiBianHao(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setJiQiDunWei(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setLuoGanZhiJing(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setSheZuiZhiJing(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setChanPinMingCheng(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setChanPinBianHao(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setKeHuLiaoHao(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setChanPinBanBen(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setYuanLiaoMingCheng(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setYuanLiaoLiaoHao(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setYuanLiaoGongYingShang(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setRLDJRDS(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setGanZaoWenDu(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setGanZaoShiJian(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setYuanLiaoHanShuiFen(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setChengXingWenDu(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setMuJuWenDu(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setSheChuYaLi(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setSheChuShiJian(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setSheChuSuDu(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setBaoYaYaLi(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setBaoYaShiJian(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setSuoMuLi(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setKaiHeMuShiJian(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setLengQueShiJian(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setLuoGanSuDu(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setDingTuiChuShiJian(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setBeiYa(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HeadInfoResbean entity, long rowId) {
        entity.setHeadInfoId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HeadInfoResbean entity) {
        if(entity != null) {
            return entity.getHeadInfoId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HeadInfoResbean entity) {
        return entity.getHeadInfoId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
